### ISSUE TITLE
Navigation Bar Styling - issue keeping contents on one line

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/navigation-highlight#1]
@thomasjbradley

I'm having trouble styling my horizontal navigation bar. When I have it set for (what I assume is) the correct text size (1.125em), I can't fit all four list elements on the same line, whilst also maintaining the correct padding/border styling. (There are some other styling problems further down in the document, but they're cascading from my navigation bar problems, so I'm less concerned about those at the moment.)

What am I doing incorrectly?

**Comment by thomasjbradley** [comment]
Did you figure the problems out? I downloaded it and dropped it into Markbot and it passes.

**Comment by MacKenzieRose** [comment]
Well, I've violated the styling requirements for padding in a few places in the code, so it passes, but is not technically in the parameters of the assignment. Is that acceptable?

**Comment by thomasjbradley** [comment]
Yeah, that’s completely acceptable. Sometimes, based on where you add the `font-size` or `line-height` or whatever, it causes the numbers to be different. So you just have to adjust things to make it work.

**Comment by MacKenzieRose** [comment]
Sounds great; thank you!
